services: docker
language: bash

env:
  - VERSION=1.13.11-alpine
  - VERSION=1.15.8-alpine
  - VERSION=1.17.0-alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$DOCKER_USERNAME/le-nginx:${VERSION}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$image"

after_script:
  - docker images
