services: docker
language: bash

env:
  - VERSION=1.13.11-alpine

install:
    - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="le-nginx:${VERSION}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
    - docker images
